### ISSUE TITLE
Non-standard char '変革' in user agent let some web server not work

### ISSUE THREAD

**Issue by coddoge** [henkaku/henkaku#10]
After install the HENkaku.
In vita browser, I got the useragent , and it contains  Non-standard char '変革'.
It let some web site returned HTTP error 502.
Suggest  change to Latin alphabet `HENkaku' to fix it. 

This is my user agent in vita web browser
Mozilla/5.0 (PlayStation Vita 3.60)(**変革**-6) AppleWebkit/537.73 (KHTML, like Gecko) Silk/3.2

**Comment by yifanlu** [comment]
What sites?

**Comment by coddoge** [comment]
c9.io

**Comment by vxbinaca** [comment]
Wouldn't this also work as a tell for Sony to see who's accessing things with a hacked console?

**Comment by xyzz** [comment]
Sony already knows.

**Comment by yifanlu** [comment]
Fixed in latest taiHENkaku beta.
