### ISSUE TITLE
File decryption routine in Payload.c is incompatible with activated testkit/devkit

### ISSUE THREAD

**Issue by mathieulh** [henkaku/henkaku#105]
The piece of code below  (within payload.c) is not compatible with an activated testkit/devkit causing an error upon loading henkaku and h-encore on those devices.

The routine expects an error to occur before taihen modules are loaded and sets g_homebrew_decrypt to 1, if g_homebrew_decrypt is set to 1 it will then set the modules with root privileges by adding the 0x40 value to the module's flags, on the other end, this does not happen when g_homebrew_decrypt is set to 0.

Activated development units however natively allow fself to be loaded, which does not result in an error despite taihen modules not being loaded and patches not performed, and will therefore not use the 0x40 root flag value, this will result in the C2-12848-3 error later on in the henkaku chain (see pictures below).

```
// setup file decryption
unsigned hook_sbl_F3411881(unsigned a1, unsigned a2, unsigned a3, unsigned a4) {
	LOG("sbl_F3411881(0x%x, 0x%x, 0x%x, 0x%x)", a1, a2, a3, a4);

	unsigned res = hook_resume_sbl_F3411881(a1, a2, a3, a4);
	LOG("sbl_F3411881: %x", res);
	unsigned *somebuf = (unsigned*)a4;
	u64_t authid;

	if (res == 0x800f0624 || res == 0x800f0616 || res == 0x800f0024 || (res >= 0x800f0b30 && res <= 0x800f0b3f)) {
		DACR_OFF(
			g_homebrew_decrypt = 1;
		);
	// BEGIN 3.60
		somebuf[42] = 0x40;
	// END 3.60

		return 0;
	} else {
		DACR_OFF(
			g_homebrew_decrypt = 0;
		);
	}
	return res;
}

```
![20180701_131434](https://user-images.githubusercontent.com/203427/42133884-801cc96a-7d31-11e8-9a9d-250881748dcb.jpg)

![20181127_131434](https://pbs.twimg.com/media/DHcxZs0XgAA0zik.jpg)

**Comment by DaveeFTW** [comment]
This is out of scope, we won't be supporting testkit/devkit.

**Comment by CelesteBlue-dev** [comment]
After running HENkaku R12:
On unactivated DevKit in DevMode: no error when launching any homebrew.
On activated DevKit in DevMode: error C2-12848-3 when launching any homebrew.
On DevKit in Release Mode: no error when launching any homebrew.
