### ISSUE TITLE
PSN functions

### ISSUE THREAD

**Issue by jack980517** [henkaku/henkaku#13]
Some PSN features, like purchasing free games, activating the device, and syncing trophy, doesn't work under henkaku's spoofing. Is this the intended behavior? Is it possible to make these work?

**Comment by yifanlu** [comment]
No, can someone else confirm the issue?

**Comment by gnmmarechal** [comment]
Huh, that's strange, it's been working for me so far.

**Comment by jack980517** [comment]
More info: I'm in China, and can successfully use the Friend and Messages apps without problems, as well as browing the PS Store. However when I try to "purchase" a free game, the PS store "freezes" (as in, not reacting to any user input) as if it was preparing for the download for a long time (~2min) and then timeout.
Activating the device for PS Mobile (I know this platform has been discontinued) returns a DNS error on my first try when my settings is auto for the DNS address. After I manually set one, the error returned is instead timeout. What's stranger is that, after this timeout prompt, I can successfully open the PSM games again (I already put tm0:/psmdrm/act.dat before my attempt).
Syncing trophy is stuck for ~1min at 40% and then returns a timeout.

**Comment by Naville** [comment]
UK. Nothing strange here.

Probably a issue of CN 's GFW

**Comment by jack980517** [comment]
I know, that's why I mentioned I'm in China. Problem is, I tried setting the HTTP proxy to my computer which is running ShadowSocks, and this should bypass the GFW. I can even use LiveTweet this way.

**Comment by jack980517** [comment]
Sorry, false alarm. Changed to another network environment and things work.
