### ISSUE TITLE
Just an idea to improve the recent PSV BRICK incident

### ISSUE THREAD

**Issue by cainwcm** [henkaku/henkaku#15]
1st, sorry to bring out this issue twice and in the sense of pirating the game, but what i'm thinking is actually even homebrew also will cause this issue, right? Correctly me if i'm wrong, but don't piss off and conclude this in the wrong way, since my intention is to provide an idea on HOW the idiot user able to see what is going-on when launching eboot/plugin if it's having abnormal behavior at the back-end.

**Comment by yifanlu** [comment]
As long as you install homebrews with vitashell/molecularshell you will be prompted if the vpk is unsafe. Please do not spam this repo again.
