### ISSUE TITLE
App folder dissapears from ux0:/ when on taiHenkaku B3

### ISSUE THREAD

**Issue by shale1337** [henkaku/henkaku#19]
MolecularShell 1.42 doesn't see folders on both Henkaku and taiHenkaku B3. VitaShell 1.41 doesn't see folders only on taiHenkaku B3. Though everything works.
All pics taken on taiHenkaku B3.

![2016-11-09-010734](https://cloud.githubusercontent.com/assets/23346769/20119402/72350f2e-a619-11e6-93a3-fc3be3d5cc4a.jpg)
![2016-11-09-011929](https://cloud.githubusercontent.com/assets/23346769/20119789/f792d2ea-a61a-11e6-87ff-1c20e90d3cdd.jpg)
![2016-11-09-012124](https://cloud.githubusercontent.com/assets/23346769/20119799/00399e9c-a61b-11e6-9f61-10f93dadcfae.jpg)

**Comment by yifanlu** [comment]
https://gist.github.com/yifanlu/73078322a2201ee32f3ae0903a3e4b65

Please read the release notes before using the beta.

> * taiHENkaku now disables unsafe homebrew by default. See [this PSA](https://gist.github.com/yifanlu/3b36b987c9099b620c5b65ce8e93801d).
