### ISSUE TITLE
stage2.go and stage2.php should behave the same?

### ISSUE THREAD

**Issue by psychowood** [henkaku/henkaku#2]
Hi,
is it normal that for the same request (i.e. `?a1=8a002000&a2=81b009f0&a3=e0002a30&a4=81200660&&a5=e0640280&a6=e0622fc0&a7=e0024ac0&` ) and with the same stage2.bin file I'm getting two different payloads from the go and php implementations?

Thanks

[go.output.zip](https://github.com/henkaku/henkaku/files/408052/go.output.zip)
[php.output.zip](https://github.com/henkaku/henkaku/files/408053/php.output.zip)

**Comment by psychowood** [comment]
Fyi, the Go implementation is working correctly. PHP was served from a windows machine, if it matters.

**Comment by yifanlu** [comment]
I think they should be the same. Does PHP work? If not, your PHP might be misconfigured.

**Comment by pythonicca** [comment]
I noticed this as well. I'm not a PHP guru but in my environment PHP had a hard integer limit which it silently returned when the value was exceeded.  (there's no outward indication that your values have been replaced and stage2.php doesn't explicitly check for this).

(Example) if stage2.php is passed these parameters:

`a1=89f02000&a2=81b009a0&a3=e000dd00&a4=811c0cc0&&a5=e0607c80&a6=e01302b0&a7=e0047bf0&`

a1-a7 values are all returned as 2147483647 and the binary created won't function the way it was intended.

The culprit in stage2.php is:

`$args[$i] = intval($_GET["a$i"], 16);`

An option might be to convert it to a string instead but that might require some changes elsewhere as well..
```
function hex2dec($hex)
{
    $dec = 0;
    $len = strlen($hex);
    for ($i = 1; $i <= $len; $i++) {
        $dec = bcadd($dec, bcmul(strval(hexdec($hex[$i - 1])), bcpow('16', strval($len - $i))));
    }
    return $dec;
}

$args[$i] = hex2dec($_GET["a$i"]);
```

**Comment by xyzz** [comment]
can we just remove the PHP version? the Go one is very simple to run

**Comment by psychowood** [comment]
Especially with a (hint hint :) ) java version [available](https://github.com/psychowood/henkaku-java).

**Comment by pythonicca** [comment]
If we could get a python implementation of stage2 it would be even simpler (with Python being the sole requirement). If whoever wrote _preprocess.py_ and _write_pkg_url.py_ could also write a working _stage2.py_ (that outputs the same binary as the go version) I can contribute the code I've already written that ties everything together.

**Comment by yifanlu** [comment]
This whole package is for hackers and tinkerers, so if you have a suggestion, make it and send a pull request :)

**Comment by xyzz** [comment]
You don't need these files anymore, since we just require static webserver now.
