### ISSUE TITLE
Getting error 80871007 installing any vpk with Beta 5

### ISSUE THREAD

**Issue by Rosearia** [henkaku/henkaku#24]
I just come back to vita, I'll explain what I did in order of events that may or may not have caused this:

-Opened molecular shell, was on version 0.91?- asked to update, it updated to 1.41. Flow's VitaShell app also updated to 1.41 too.
-Reset vita
-Installed latest stable henkaku.
-Saw adrenaline online.
-Installed latest beta.henkaku (b5) vita crashed before finishing.
-Tried again, installed fine. MolecularShell is now at 1.42, VitaShell is still 1.41
-Tried to install vpks and error 80871007 comes up just after 100% with all vpks (safe homebrew enabled) either on or off.

**Comment by bocaskt** [comment]
Me too.

**Comment by finalgravity525** [comment]
Same error i received :(

**Comment by bosshunter** [comment]
Yup, same here. Error 0x80871007.

**Comment by martin26765** [comment]
I can confirm. I try different vpks and none install with last tai beta5. Working ok with stable henkaku.
