### ISSUE TITLE
2016-11-26 BETA : Error 80029537 when installing a .vpk

### ISSUE THREAD

**Issue by CelesteBlue-dev** [henkaku/henkaku#29]
With VitaShell 1.42 (or MolecularShell 1.42) :
Install a .vpk.
0%->100%. Then Error 80029537.

**Comment by yifanlu** [comment]
This happens for any vpk?

**Comment by CelesteBlue-dev** [comment]
Yes it was but you fixed it this morning by updating taiHENkaku
Good work !
