### ISSUE TITLE
restart browser?

### ISSUE THREAD

**Issue by Nibbles-san** [henkaku/henkaku#31]
Alright, this may sound bizarre but when attempting to install tai-henkaku the browser error of "restart the browser" occurs. But when I do it repeats the error message even after restart and even rebuilding my database.

**Comment by yifanlu** [comment]
You just have to keep trying.

**Comment by gnmmarechal** [comment]
Even stable HENkaku does that sometimes.

**Comment by Nibbles-san** [comment]
ok will do
