### ISSUE TITLE
Version string missing on PDEL

### ISSUE THREAD

**Issue by fate6** [henkaku/henkaku#35]
System works fine but still found it funny that it causes this.

Used taiHENkaku B6 so no idea on previous ones.

**Comment by yifanlu** [comment]
what about PTEL?

**Comment by fate6** [comment]
Not sure as I don't have that one yet but since both show you the full version string I assume the issue would be the same?

3.600.011 becomes -

**Comment by yifanlu** [comment]
Weird. I imagine the issue is that a modified version string doesn't play well with the extended version.

**Comment by yifanlu** [comment]
Can't find an obvious fix and I don't think it's worth wasting time on.
