### ISSUE TITLE
Provide libHENkaku_stub

### ISSUE THREAD

**Issue by TheOfficialFloW** [henkaku/henkaku#38]

**Comment by d3m3vilurr** [comment]
[this](https://github.com/d3m3vilurr/vitatoolchain/blob/f3dc524/scripts/018-henkaku.sh) ?

**Comment by yifanlu** [comment]
It will be in the releases. Hopefully automatically soon, but since I don't plan to add new exports soon, this should be good enough: https://github.com/henkaku/henkaku/releases/tag/stubs-r6
