### ISSUE TITLE
taiHEN won't update to BETA-8 stays on Beta-7

### ISSUE THREAD

**Issue by metal-velcro** [henkaku/henkaku#40]
I have deleted molecularshell and started from scratch several times. Also I don't have access to most ux0:\ folders like the one to grab the screen shot i took to show. I have unsafe homebrew enabled and molecularshell 1.43 and vitashell .43 both show the exact same folders. I have deleted the bubble, rebuilt database then a fresh install but still the same

**Comment by yifanlu** [comment]
Can you take a picture (with your phone or something) of the build string when the installer launches?

**Comment by metal-velcro** [comment]
Sure check out this link but I got Vitashell working using the one from his github. 

http://www.psx-place.com/threads/taihenkaku-beta-8-released-stable-for-daily-use-now.11954/#post-65659

**Comment by metal-velcro** [comment]
![2016-12-20-185019](https://cloud.githubusercontent.com/assets/20314349/21376369/614f8e1e-c702-11e6-9d80-8b30da50c078.jpg)

![2016-12-20-221116](https://cloud.githubusercontent.com/assets/20314349/21376372/64c50f88-c702-11e6-86f3-f97f59caf498.jpg)

**Comment by yifanlu** [comment]
You are on beta 8.

**Comment by metal-velcro** [comment]
Why does it say HENkaku 7 then on installer? I saw 7 then the B which I assume was beta 8 so I was confused. Thanks for clearing that up.

**Comment by yifanlu** [comment]
It's release 7 beta 8.
