### ISSUE TITLE
Save issue after a day in standby

### ISSUE THREAD

**Issue by werdy77** [henkaku/henkaku#41]
Experienced the save issue (which was fixed earlier if i can remember) with the latest taiHENkaku version.

- TaiHENkaku beta 8 loaded from email (installed with beta offline installer).
- Run game Steins;Gate 0 (PCSB01012 with english patch).
- Put Vita to standby for a day. Tried with less intervals (like half day) but it seems 24h required for the bug.
- Initiated saving game and got C2-2004-6 "Could not save the file." error message. After dismissal (hit ok) got the same message again and again.

Had save issue (without error message, simply missing progress at next launch) with MotorStorm RC too.

![vita-error](https://cloud.githubusercontent.com/assets/11886025/21472126/fbea6220-caca-11e6-9e4e-29653dd94104.jpg)

**Comment by yifanlu** [comment]
Not henkaku related. This is an issue with game dumpers. Buy your games.

**Comment by werdy77** [comment]
I see. Thanks for the info. Are current dumpers (Vitamin or Mai Dump Tool) still affected with this?
Anyway i can't buy english patched games :(
