### ISSUE TITLE
Latest self-hosting files missing from 'releases' page

### ISSUE THREAD

**Issue by pythonicca** [henkaku/henkaku#43]
From what I understand v1.6 (Release 7) is now currently live on [http://go.henkaku.xyz](http://go.henkaku.xyz) but I don't see the self-hosting files for it on [https://github.com/henkaku/henkaku/releases](https://github.com/henkaku/henkaku/releases).

Can we get an updated release?

Thank you!

**Comment by yifanlu** [comment]
That is no longer supported as henkaku's source has been released. Just compile henkaku.
