### ISSUE TITLE
Error installing Henkaku R7

### ISSUE THREAD

**Issue by TheFatsiky** [henkaku/henkaku#44]
I have this error and i can't install henkaku R7
![2017-01-10-114053](https://cloud.githubusercontent.com/assets/25029436/21802377/8d309cfa-d736-11e6-970f-99916bd6a8a0.jpg)
![2017-01-10-114114](https://cloud.githubusercontent.com/assets/25029436/21802378/8d33c466-d736-11e6-8ce4-cd2b43ae4b24.jpg)
![2017-01-10-114122](https://cloud.githubusercontent.com/assets/25029436/21802379/8d396330-d736-11e6-9b26-8b88dc3bd971.jpg)
![2017-01-10-114134](https://cloud.githubusercontent.com/assets/25029436/21802380/8d3d1c64-d736-11e6-8307-48e79e0889f4.jpg)
![2017-01-10-114147](https://cloud.githubusercontent.com/assets/25029436/21802381/8d403e3a-d736-11e6-8cfb-80311122d929.jpg)
![2017-01-10-114152](https://cloud.githubusercontent.com/assets/25029436/21802382/8d45e254-d736-11e6-8df1-2636cf6c374c.jpg)

**Comment by yifanlu** [comment]
You are running an old build (12/26). Are you running the offline installer without updating it?

**Comment by TheFatsiky** [comment]
Thank you! It's resolved, I used a DNS server in my network and I switched another network and it worked. Thanks a lot.
