### ISSUE TITLE
Release 7 ??

### ISSUE THREAD

**Issue by Vitauser** [henkaku/henkaku#45]
Hello,
Will there a henkaku tainhenkaku release 7 for offline hosting ? Its still release 6 but release 7 is online. Or is the offline hosting dead ?

**Comment by yifanlu** [comment]
No. just compile it.

**Comment by Vitauser** [comment]
How can i do this ?

**Comment by Vitauser** [comment]
It would be nice when you can help me please.

**Comment by gnmmarechal** [comment]
It would be nice for you to read the README.

**Comment by Vitauser** [comment]
it would be nice for you when you can explain how to do it bewcause i have read the readme and i dont know what to do !! The Release 6 works flawlessly here on my server but what should i do that release 7 will work ?? Again can you please explain what to do ? Thank You

**Comment by yifanlu** [comment]
Ask around in https://forums.vitasdk.org/viewforum.php?f=25 and see if anyone can help.
