### ISSUE TITLE
`sceAppMgrDestroyOtherApp()` takes 0 argument, but 1 argument is used

### ISSUE THREAD

**Issue by devnoname120** [henkaku/henkaku#46]
https://github.com/vitasdk/vita-headers/commit/86f6c858575ec29af7fa72cd9f8e97167d96f503#diff-25be613a5be62551eb6f11e86aa960b3R70

Faulty usage: https://github.com/henkaku/henkaku/blob/2a72b467ea9f1773bef44230777e86681e862bc4/bootstrap/bootstrap.c#L524

**Comment by yifanlu** [comment]
Please submit a PR. I won't be able to change the code for a while.

**Comment by devnoname120** [comment]
#47
