### ISSUE TITLE
Games that need 3.61 and up need to be spoofed 

### ISSUE THREAD

**Issue by jcmejia** [henkaku/henkaku#53]
Yeah its a firmware restrictions I tried to run gun gun pixies but it gives me a error code c1-6703-6 I tried it on my playstation tv running henkaku but on my playstation vita running the latest firmware it does work but not on my playstation tv running henkaku

**Comment by xyzz** [comment]
#11

**Comment by yifanlu** [comment]
So you see a locked issue purposely there to discourage duplicate reporting and what do you do? Go ahead and post a duplicate with the same title. Smh...

**Comment by jcmejia** [comment]
Actually I didn't do it on purpose there are also recent games that need
3.63 if not it doesn't start it gives a error code
