### ISSUE TITLE
Henkaku does not support more than 2 plugins enabled at the same time. 

### ISSUE THREAD

**Issue by TheRadziu** [henkaku/henkaku#56]
Already confirmed here: https://www.reddit.com/r/vitahacks/comments/68rjom/trying_to_find_out_why_enabling_multiple_plugins/ , on twitter and by myself that games (no matter whether it is mai/vitamin/legit game) won't go past splash screen (in case of 3 plugins enabled) or will crash(in case of 4 or more plugins enabled - _I haven't check this part myself since 3 plugins at once are already not working_).
To be sure I checked if games work with only 2 plugins enabled (in any pairing) and they do, so It certainly is an issue with 3 or more plugins enabled at once. 

~~Also it seems this issue is even worse in case of adrenaline v4, it gives black screen if (in my case) any additional plugin (tried trackplug and then vitabattery) is added. I thought it might be adrenaline's compatibility with tai plugins issue, but after all it might be related to this one.~~
_This part has been already answered to by TheFlow_
 
**It is easy to reproduce this issue** - just add 3 or 4 plugins under *ALL (probably 3/4 plugins under certain ID will give the same result) and run the game with all 3/4 plugins enabled.  
If that matters in my case the plugins are: vitabattery, oclock and trackplug.

**Comment by yifanlu** [comment]
To confirm, you have tried all combinations of enabling just two plugins and that works?

**Comment by yifanlu** [comment]
Also is this a recent issue? (Did this work fine before the recent update?)

**Comment by TheOfficialFloW** [comment]
Memory for pspemu is limited, that's why you can't have additional plugins running with Adrenaline.

**Comment by yifanlu** [comment]
@TheRadziu can you test the latest henkaku and see if this is still an issue?

**Comment by TheRadziu** [comment]
It works for me now with 4 plugins enabled. (5 to be honest, but freescreenshots seems not to be working, but I have a feeling that is an issue with plugin itself rather than henkaku).

Thanks for the fix!
