### ISSUE TITLE
MolecularShell outdated / Henkaku downgrades 1.61 Molecularshell to 1.43 

### ISSUE THREAD

**Issue by TheRadziu** [henkaku/henkaku#57]
First, Id like to say I know Molecularshell have auto updates disabled so it isn't the same as vitashell (at least that is what [/henkaku/vitashell](https://github.com/henkaku/VitaShell) description says).

Right now Molecularshell(v1.43) is pretty outdated in comparison to Vitashell(1.61) and that version lacks many new features(like USB support) or newer bugfixes. 
Of course, it is possible to replace Molecular eboot with vitashell eboot to "update" it and everything will work as it should, BUT everytime henkaku is enabled/executed (via online method) CRC check fails and it redownloads 1.43 eboot. 
I simply do not want to have installed both molecular shell and vitashell because they both have pretty much same functionality(excluding henkaku-related options in molecular) and keep only one of these updated.

My suggestions are: 
-Update Molecular shell to 1.61 and keep an eye for future vitashell's updates to keep it updated
or
-Give TheFlow some ability to keep molecularShell updated on henkaku server (inc. ability to update CRC sum)
or
-Rework how CRC check does it job to exclude force downgrading newer eboots. 

Cheers!

**Comment by yifanlu** [comment]
I've commented on this before

> We've discussed this internally a while ago and ultimately, we decided to hard fork VitaShell because we wanted a stable file-manager that is as basic as possible. By current design, the henkaku itself is installed in the directory for molecularShell--that way you can remove all henkaku files by removing the molecularshell bubble. That means updating molecularshell has to go through our update mechanism while VitaShell gets more regular updates through its own updater.

> We also don't want to include the VitaShell kernel plugins with every molecularShell installation. Kernel resources are very sacred and any unneeded module (even if limited to just one app) can cost performance and battery life. This is why we give the users the choice between a bare-bones molecularShell and the full featured VitaShell.

Unfortunately you're gonna have to live with it. Yes, you can save 1MB of space and one icon space, but for people who don't need the fancy VitaShell features, there's no point wasting kernel memory and battery life, which imo is much more important.

**Comment by TheRadziu** [comment]
Thanks for your reply. 
In that case, how about additional henkaku setting that will turn turn off crc check for people like me?

**Comment by yifanlu** [comment]
No, that would require work.
