### ISSUE TITLE
Modifying psp emulator on vita to enhancing the quality.

### ISSUE THREAD

**Issue by Fadi5555** [henkaku/henkaku#8]
Hi there. I'm just wondering if you can modifying psp emu on vita through henkaku to could play psp games in hd like ppsspp. I guess you can change the quality of the psp emu. Because it's so pixelated. I hope you can do that.

**Comment by gnmmarechal** [comment]
I dont see this happening anytime soon.

**Comment by SONIC3D** [comment]
> ...play psp games in hd like ppsspp

I think what you are expecting a graphics HLE implementation in PSP emulation.That's not what Henkaku intended to do.

**Comment by yifanlu** [comment]
Henkaku is not about adding features to the vita. It only enables homebrew.

**Comment by MikiraSora** [comment]
I perfer unlock unity3d for psm than psp emu....

**Comment by coddoge** [comment]
I want to runing C# in Vita too.
Tried compile mono in VitaSDK but failed. 
Its has no standard c function lib, all that sceXXXXX.
May need a libc bridge library to adapt it.
