### ISSUE TITLE
Building Web server from source fails

### ISSUE THREAD

**Issue by ivdok** [henkaku/henkaku#88]
I've thoroughly checked the prerequisites, but I can't seem to start the building process. Here's the [gist](https://gist.github.com/ivdok/2e6103931b3a6ab47639245018f84836), which contains all my edits and output. At first, I've had an error regarding Bootstrap component (using sample.config.in), but right now I can't even reach that phase. Either I'm missing something, or my config is wrong somewhere, can't hazard a guess what exactly.
I'm building on Manjaro Linux host (4.14.0-1-MANJARO SMP PREEMPT Wed Nov 8 23:54:55 UTC 2017) if that's needed.

**Comment by yifanlu** [comment]
Ugh someone probably broke the sdk. Try an older prebuilt. One from when henkaku was last updated.

**Comment by ivdok** [comment]
It's the one mentioned in the "build" section? Unfortunately, the link is down (502 error, tried both local ISP and through Tor). I'm guessing the site is operated by @DaveeFTW, so might as well mention him. Thinking of checking out earlier commits of vdpm, just not sure which time period I'm looking for. Maybe Jun/July, 2017 will work, who knows.

**Comment by xyzz** [comment]
Should work now after the rewrite.
