### ISSUE TITLE
Some questions about building

### ISSUE THREAD

**Issue by Yoti** [henkaku/henkaku#97]
1) Where to get a PSN_PASSPHRASE? May you post your own used on release build at henkaku.xyz?

2) After building henkaku "output\offline" directory is empty. Do I need any additional steps?

3) After building I got version tag as "R11/v10.2-15-g784e483" instead of "R11/v11". Outdate src here?

**Comment by yifanlu** [comment]
1. You can probably extract it from our binaries. We do not include it for legal reasons.
2. Offline installer has been removed since ensō is the preferred way now. If you want to use it, sync to a previous commit.
3. The tag name was probably not updated.

**Comment by Yoti** [comment]
1. That one from MLThaku is legit?

**Comment by yifanlu** [comment]
I have no idea what they do, ask them.

**Comment by Yoti** [comment]
It's in "sd2vita.config.in" here: https://github.com/MLTHaKu/MLTHaKu-HAX

**Comment by CelesteBlue-dev** [comment]
yes that's it
