### ISSUE TITLE
Henkaku 3.60 Error "Files are corrupted"

### ISSUE THREAD

**Issue by LuzBelitoLP** [henkaku/henkaku#98]
Sorry for my English (

The console had the henkaku installed, install the henkaku enso and then as it was linked to a PSN account, restore it ...

After that, I asked myself if I wanted to transfer some files from the internal memory to the external one and that's the way ...

Now I am trying to install the henkaku of 0 but I am throwing these errors and I do not know how to solve them.

ERROR: taiHenkaku files are corrupted, trying to reinstall

Here the link with the image

https://drive.google.com/file/d/1rkHeENdpARuXQOKyPI5OaikeQqYp4n0O/view

**

> Starting…
> taihen.skprx CRC32:0, latest:a360e2be
> downloading http//henkaku.xyz/pkg/taihen.skprk
> 
> sceHttpReadData error! 0x80431068  molecularshell CRC32:0, latest:714ce026
> Getting latest version…
> 
> downloading http//henkaku.xyz/pkg/eboot.bin
> sceHttpReadData error! 0x80431068 
> 
> etc… etc…
> 
> ERROR: taiHENkaku files are corrupted, trying to reinstall (2 tries left)…

**

**Comment by yifanlu** [comment]
It is a problem with your internet access.

**Comment by LuzBelitoLP** [comment]
Could you tell me something else please? it's really important for me to be able to solve it ...

Put in DMZ my IP in the rotuer?
Change any settings in the Firewall?

Thank you

**Comment by devingDev** [comment]
Try with another connection.

**Comment by yifanlu** [comment]
This is not a support forum.
